server:
    port: ${PORT:8080}
spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        password: ${JDBC_DATABASE_PASSWORD:}
        url: ${JDBC_DATABASE_URL:}
        username: ${JDBC_DATABASE_USERNAME:}
        hikari:
            connection-timeout: 80000
            maximum-pool-size: 10
    servlet:
        multipart:
            max-file-size: 1MB
            max-request-size: 5MB

    jpa:
        database-platform: ${SPRING_JPA_DATABASE-PLATFORM:}
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                format_sql: true









#----------------------BEFORE I MIGRATE TO POSTGRESQL----------------------------
#logging:
#    level:
#        blog: WARN
#        org: WARN
#        org.hibernate.sql: DEBUG
#server:
#    error:
#        whitelabel:
#            enabled: false
#spring:
#    datasource:
#        driverClassName: com.mysql.cj.jdbc.Driver
#        password: ${myPassword}
#        url: jdbc:mysql://localhost:3306/GuestHouse?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
#        username: ${myUsername}
#    jpa:
#        hibernate:
#            ddl-auto: create-drop
#        open-in-view: false
#        properties:
#            hibernate:
#                dialect: org.hibernate.dialect.MySQL8Dialect
#                format_sql: true
